USDT_WARNING_AMOUNT = 10
USDT_CRITICAL_AMOUNT = 3
EXCHANGE_1_ORDERBOOK_TIMEOUT_MS = 10000
TIME_WAIT_AFTER_CLOSE_ORDERS_S = 5
DELAY_BETWEEN_ORDER_FETCH = 2
RETRY_COUNT = 5
RETRY_TIMEOUT = 30
FAILED_ORDER_COUNT = 3

TOKEN_BALANCE_DELTA = 3

EXCHANGE_1_ORDER_DOWNTIME = 5 * 60
EXCHANGE_2_ORDER_DOWNTIME = 5 * 60

BUILD_VERSION = 1
EMPTY_DEPTH_TIME = 5 * 60
ORDER_PRICE_DEVIATION_PERCENT = 1
